export const BUY_WALLET_REQUEST = "BUY_WALLET_REQUEST";
export const BUY_WALLET_SUCCESS = "BUY_WALLET_SUCCESS";
export const BUY_WALLET_FAILURE = "BUY_WALLET_FAILURE";

export const EXCHANGE_WALLET_REQUEST = "EXCHANGE_WALLET_REQUEST";
export const EXCHANGE_WALLET_SUCCESS = "EXCHANGE_WALLET_SUCCESS";
export const EXCHANGE_WALLET_FAILURE = "EXCHANGE_WALLET_FAILURE";

export const TRANSFER_WALLET_REQUEST = "TRANSFER_WALLET_REQUEST";
export const TRANSFER_WALLET_SUCCESS = "TRANSFER_WALLET_SUCCESS";
export const TRANSFER_WALLET_FAILURE = "TRANSFER_WALLET_FAILURE";
