export const PLOT_CREATE_REQUEST = "PLOT_CREATE_REQUEST"
export const PLOT_CREATE_SUCCESS = "PLOT_CREATE_SUCCESS"
export const PLOT_CREATE_FAILURE = "PLOT_CREATE_FAILURE"

export const PLOT_DELETE_REQUEST = "PLOT_DELETE_REQUEST"
export const PLOT_DELETE_SUCCESS = "PLOT_DELETE_SUCCESS"
export const PLOT_DELETE_FAILURE = "PLOT_DELETE_FAILURE"

export const GET_ALL_PLOTS_REQUEST = "GET_ALL_PLOTS_REQUEST"
export const GET_ALL_PLOTS_SUCCESS = "GET_ALL_PLOTS_SUCCESS"
export const GET_ALL_PLOTS_FAILURE = "GET_ALL_PLOTS_FAILURE"

export const GET_USER_PLOTS_REQUEST = "GET_USER_PLOTS_REQUEST"
export const GET_USER_PLOTS_SUCCESS = "GET_USER_PLOTS_SUCCESS"
export const GET_USER_PLOTS_FAILURE = "GET_USER_PLOTS_FAILURE"

export const USER_LIKE_PLOT_REQUEST = "USER_LIKE_PLOT_REQUEST"
export const USER_LIKE_PLOT_SUCCESS = "USER_LIKE_PLOT_SUCCESS"
export const USER_LIKE_PLOT_FAILURE = "USER_LIKE_PLOT_FAILURE"

export const LIKE_PLOT_REQUEST = "LIKE_PLOT_REQUEST"
export const LIKE_PLOT_SUCCESS = "LIKE_PLOT_SUCCESS"
export const LIKE_PLOT_FAILURE = "LIKE_PLOT_FAILURE"

export const FIND_PLOT_BY_ID_REQUEST = "FIND_PLOT_BY_ID_REQUEST"
export const FIND_PLOT_BY_ID_SUCCESS = "FIND_PLOT_BY_ID_SUCCESS"
export const FIND_PLOT_BY_ID_FAILURE = "FIND_PLOT_BY_ID_FAILURE"

export const REPLOT_REQUEST = "REPLOT_REQUEST"
export const REPLOT_SUCCESS = "REPLOT_SUCCESS"
export const REPLOT_FAILURE = "REPLOT_SUCCESS"

export const COLLECT_REQUEST = "COLLECT_REQUEST"
export const COLLECT_SUCCESS = "COLLECT_SUCCESS"
export const COLLECT_FAILURE = "COLLECT_FAILURE"

export const VIEW_PLOT_REQUEST = "VIEW_PLOT_REQUEST"
export const VIEW_PLOT_SUCCESS = "VIEW_PLOT_SUCCESS"
export const VIEW_PLOT_FAILURE = "VIEW_PLOT_FAILURE"


export const UPDATE_PLOT_REQUEST = "UPDATE_PLOT_REQUEST"
export const UPDATE_PLOT_SUCCESS = "UPDATE_PLOT_SUCCESS"
export const UPDATE_PLOT_FAILURE = "UPDATE_PLOT_FAILURE"
